name: energise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_maps_flutter: ^2.6.1
  flutter_rating_bar: ^4.0.1
  share_plus: ^9.0.0
  url_launcher: ^6.2.6
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1

  #api service
  http: ^1.2.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1024x1024.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Circe
      fonts:
        - asset: assets/fonts/Circe-Light.ttf
          weight: 300
        - asset: assets/fonts/Circe-Regular.ttf
          weight: 400
        - asset: assets/fonts/Circe-Bold.ttf
          weight: 700
        - asset: assets/fonts/Circe-ExtraBold.ttf
          weight: 800
